
services:
  backend:
    build:
      context: ./backend
    expose:
      - "4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_BASE_URL=https://api.scalelab.easycase.site
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    expose:
      - "3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://api.scalelab.easycase.site
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    depends_on:
      - backend
    restart: always

  proxy:
    image: jonasal/nginx-certbot:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=vanujakofficial@gmail.com
    volumes:
      - ./nginx.conf:/etc/nginx/user_conf.d/default.conf:ro
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    restart: always
