server {
    listen 443 ssl;
    server_name api.scalelab.easycase.site;

    ssl_certificate /etc/letsencrypt/live/api.scalelab.easycase.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.scalelab.easycase.site/privkey.pem;

    location / {
        proxy_pass http://backend:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name scalelab.easycase.site;

    ssl_certificate /etc/letsencrypt/live/scalelab.easycase.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/scalelab.easycase.site/privkey.pem;

    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
